on: push

jobs:
  release:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'        
      - 
        name: publish
        run: dotnet publish
